export const currencies = {
   USD: { name: "United States Dollar", symbol: "$" },
   EUR: { name: "Euro", symbol: "€" },
   GBP: { name: "British Pound", symbol: "£" },
   RUB: { name: "Russian Ruble", symbol: "₽" },
   JPY: { name: "Japanese Yen", symbol: "¥" },
   CNY: { name: "Chinese Renminbi", symbol: "¥" },
   AUD: { name: "Australian Dollar", symbol: "$" },
   CAD: { name: "Canadian Dollar", symbol: "$" },
   CHF: { name: "Swiss Franc", symbol: "CHF" },
   INR: { name: "Indian Rupee", symbol: "₹" },
   BRL: { name: "Brazilian Real", symbol: "R$" },
   MXN: { name: "Mexican Peso", symbol: "$" },
   IDR: { name: "Indonesian Rupiah", symbol: "Rp" },
   KRW: { name: "South Korean Won", symbol: "₩" },
   ZAR: { name: "South African Rand", symbol: "R" },
   TRY: { name: "Turkish Lira", symbol: "₺" },
   NZD: { name: "New Zealand Dollar", symbol: "$" },
   SEK: { name: "Swedish Krona", symbol: "kr" },
   NOK: { name: "Norwegian Krone", symbol: "kr" },
   DKK: { name: "Danish Krone", symbol: "kr" },
   PLN: { name: "Polish Złoty", symbol: "zł" },
   MYR: { name: "Malaysian Ringgit", symbol: "RM" },
   SGD: { name: "Singapore Dollar", symbol: "$" },
   HUF: { name: "Hungarian Forint", symbol: "Ft" },
   THB: { name: "Thai Baht", symbol: "฿" },
   ILS: { name: "Israeli New Shekel", symbol: "₪" },
   PHP: { name: "Philippine Peso", symbol: "₱" },
   RON: { name: "Romanian Leu", symbol: "lei" },
   BGN: { name: "Bulgarian Lev", symbol: "лв" },
   KZT: { name: "Kazakhstani Tenge", symbol: "₸" },
   VND: { name: "Vietnamese Dong", symbol: "₫" },
   CLP: { name: "Chilean Peso", symbol: "$" },
   ARS: { name: "Argentine Peso", symbol: "$" },
   COP: { name: "Colombian Peso", symbol: "$" },
   EGP: { name: "Egyptian Pound", symbol: "£" },
   MAD: { name: "Moroccan Dirham", symbol: "د.م." },
   QAR: { name: "Qatari Rial", symbol: "ر.ق" },
   AED: { name: "United Arab Emirates Dirham", symbol: "د.إ" },
   LKR: { name: "Sri Lankan Rupee", symbol: "Rs" },
   BDT: { name: "Bangladeshi Taka", symbol: "৳" },
   PKR: { name: "Pakistani Rupee", symbol: "₨" },
   TWD: { name: "Taiwan Dollar", symbol: "NT$" },
   UAH: { name: "Ukrainian Hryvnia", symbol: "₴" },
   KWD: { name: "Kuwaiti Dinar", symbol: "د.ك" },
   OMR: { name: "Omani Rial", symbol: "ر.ع." },
   LBP: { name: "Lebanese Pound", symbol: "ل.ل" },
   YER: { name: "Yemeni Rial", symbol: "ر.ي" },
   CSD: { name: "Serbian Dinar", symbol: "Дин." },
   RSD: { name: "Serbian Dinar", symbol: "Дин." },
   MNT: { name: "Mongolian Tugrik", symbol: "₮" },
   GEL: { name: "Georgian Lari", symbol: "₾" },
   KGS: { name: "Kyrgyzstani Som", symbol: "сом" },
   AZN: { name: "Azerbaijani Manat", symbol: "₼" },
   AMD: { name: "Armenian Dram", symbol: "֏" },
   BYN: { name: "Belarusian Ruble", symbol: "Br" },
   MDL: { name: "Moldovan Leu", symbol: "lei" },
   MMK: { name: "Myanmar Kyat", symbol: "Ks" },
   MOP: { name: "Macanese Pataca", symbol: "MOP$" },
   RWF: { name: "Rwandan Franc", symbol: "R₣" },
   BIF: { name: "Burundian Franc", symbol: "Fbu" },
   XOF: { name: "West African CFA Franc", symbol: "CFA" },
   XPF: { name: "Pacific CFA Franc", symbol: "XPF" },
   GHS: { name: "Ghanaian Cedi", symbol: "₵" },
   ZMW: { name: "Zambian Kwacha", symbol: "ZK" },
   ZWL: { name: "Zimbabwean Dollar", symbol: "$" },
} as const;
